### ISSUE TITLE
Quickstart #2 doesn't run

### ISSUE THREAD

**Issue by jlpm10091** [DuendeSoftware/Samples#51]
Clean download... run

Api Error:  
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      Swashbuckle.AspNetCore.SwaggerGen.SwaggerGeneratorException: Ambiguous HTTP method for action - Api.Controllers.IdentityController.Get (Api). Actions require an explicit HttpMethod binding for Swagger/OpenAPI 3.0
      
Identity Server Error:
[00:30:53 Error] Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware
An unhandled exception has occurred while executing the request.
System.ArgumentException: The 'ClientId' option must be provided. (Parameter 'ClientId')

Web Client Error:
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.InvalidOperationException: IDX20803: Unable to obtain configuration from: 'System.String'.
       ---> System.IO.IOException: IDX20807: Unable to retrieve document from: 'System.String'. HttpResponseMessage: 'System.Net.Http.HttpResponseMessage', HttpResponseMessage.Content: 'System.String'.

**Comment by brockallen** [comment]
Why do we have swagger in the API hosts at all? Is that generated from something?

**Comment by josephdecock** [comment]
Swagger is generated by `dotnet new webapi`.

**Comment by josephdecock** [comment]
@jlpm10091 Swagger is only here because it is automatically included by Microsoft's template, and we don't actually make use of it in the quickstart docs at all. That said, we have a fix incoming for it: #47. 

Can you give us some more detail about the steps you took to create the other errors you included above? I'm not able to reproduce either of those.

**Comment by J0hnRoger** [comment]
Hello, same problem here. In the sample #2 - I run the WebClient, and I get an error: 
`InvalidOperationException: IDX20803: Unable to obtain configuration from: 'System.String'.`

Then, I checked the Program Console (Client), which works in the #1 - and I have the root problem - the following error : 
`System.ArgumentException: The 'ClientId' option must be provided. (Parameter 'ClientId')
   at Microsoft.AspNetCore.Authentication.OAuth.OAuthOptions.Validate()
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationOptions.Validate(String scheme)
   at Microsoft.AspNetCore.Authentication.AuthenticationBuilder.<>c__DisplayClass4_0`2.<AddSchemeHelper>b__1(TOptions o)
   at Microsoft.Extensions.Options.ValidateOptions`1.Validate(String name, TOptions options)
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.OptionsMonitor`1.<>c__DisplayClass10_0.<Get>b__0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Microsoft.Extensions.Options.OptionsCache`1.GetOrAdd(String name, Func`1 createOptions)
   at Microsoft.Extensions.Options.OptionsMonitor`1.Get(String name)
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.InitializeAsync(AuthenticationScheme scheme, HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationHandlerProvider.GetHandlerAsync(HttpContext context, String authenticationScheme)
   at Duende.IdentityServer.Hosting.FederatedSignOut.FederatedSignoutAuthenticationHandlerProvider.GetHandlerAsync(HttpContext context, String authenticationScheme) in /_/src/IdentityServer/Hosting/FederatedSignOut/FederatedSignoutAuthenticationHandlerProvider.cs:line 33`

Is there a secret to filled or something?

**Comment by J0hnRoger** [comment]
I figure out the problem. I don't have secrets filled, and we need it for the google OAuth2 : 
_HostingExtensions_
```
  builder.Services.AddAuthentication()
            .AddGoogle("Google", options =>
            {
                options.SignInScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme;

                options.ClientId = builder.Configuration["Authentication:Google:ClientId"];
                options.ClientSecret = builder.Configuration["Authentication:Google:ClientSecret"];
            })
```
I commented out these lines and it works perfectly. 

Sorry for the false positive

**Comment by josephdecock** [comment]
@brockallen - do you think we should comment out the google provider so that the sample will run "out of the box"?

**Comment by brockallen** [comment]
Yea, might as well. And then people will be forced to understand how to get google configured if/when they want it. Also, can we update our QS docs to mention something about it, please? TY!

**Comment by leastprivilege** [comment]
Just do an "<insert here>" for the id/secret.

**Comment by josephdecock** [comment]
@leastprivilege - That's a good idea, except we have to put in a dummy value. The handler throws if you try to configure it with the empty string for id or secret. 

@brockallen - We have a whole section in the quickstart on google auth. For the initial registration with google, we refer folks to microsoft's docs:

> See [Microsoft’s guide](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/google-logins?view=aspnetcore-6.0#create-a-google-api-console-project-and-client-id) for details on how to register with Google, create the client, and store the secrets in user-secrets. *Stop before adding the authentication middleware and Google authentication handler to the pipeline.*

**Comment by leastprivilege** [comment]
> we have to put in a dummy value

That's what I meant - IIRC our templates do the same.
